{% set name = "nbcommands" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vinayak-mehta/nbcommands/archive/v{{ version }}.tar.gz
  sha256: 2c5e0962a75ee3decff0687bf98cb5597fa6da95ec2dfa259b3512086c4cf68c

build:
  noarch: python
  number: 0
  entry_points:
    - nbblack = nbcommands._black:_black
    - nbtouch = nbcommands._touch:touch
    - nbgrep = nbcommands._grep:grep
    - nbhead = nbcommands._head:head
    - nbtail = nbcommands._tail:tail
    - nbcat = nbcommands._cat:cat
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - black
    - click
    - colorama
    - nbformat
    - pygments

test:
  imports:
    - nbcommands

about:
  home: https://github.com/vinayak-mehta/nbcommands
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Unix commands for Jupyter notebooks!
  description: |
    nbcommands bring the goodness of Unix commands to Jupyter notebooks.
  doc_url: https://nbcommands.readthedocs.io/
  dev_url: https://github.com/vinayak-mehta/nbcommands

extra:
  recipe-maintainers:
    - vinayak-mehta
