{% set name = "nbcommands" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vinayak-mehta/nbcommands/archive/v{{ version }}.tar.gz
  sha256: fd7b3cdd8d9d28e03e20a4997bd4f3ad2d50bc86f6af4b485fe7711cfe7f7b54

build:
  noarch: python
  number: 1
  entry_points:
    - nbblack = nbcommands._black:_black
    - nbtouch = nbcommands._touch:touch
    - nbgrep = nbcommands._grep:grep
    - nbhead = nbcommands._head:head
    - nbtail = nbcommands._tail:tail
    - nbcat = nbcommands._cat:cat
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - black
    - click
    - colorama
    - nbformat
    - pygments

test:
  requires:
    - python {{ python_min }}
  imports:
    - nbcommands

about:
  home: https://github.com/vinayak-mehta/nbcommands
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Unix commands for Jupyter notebooks!
  description: |
    nbcommands bring the goodness of Unix commands to Jupyter notebooks.
  doc_url: https://nbcommands.readthedocs.io/
  dev_url: https://github.com/vinayak-mehta/nbcommands

extra:
  recipe-maintainers:
    - vinayak-mehta
